### ISSUE TITLE
Error while copying media file

### ISSUE THREAD

**Issue by fireonmac** [capacitor-community/media#66] opened 2023-08-30 07:06 UTC
File: MediaPlugin
Line: 299
Code fragment: 
```
try {
    // generate image file name using current date and time
    String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmssSSS").format(new Date());
    String fileName = call.getString("fileName", "IMG_" + timeStamp);
    File expFile = copyFile(inputFile, albumDir, fileName);
    scanPhoto(expFile);

    JSObject result = new JSObject();
    result.put("filePath", expFile.toString());
    call.resolve(result);
} catch (RuntimeException e) {
    call.reject(e.getLocalizedMessage(), null, e); // I changed this line to get the error message in javascript layer.
}
```

Explanation.
Some of Android users can't download media files regardress of OS versions. 
I couldn't reproduce this error on my devices.
Error logs starting with "RuntimeException occurred ..." didn't help at all, so to check the detailed error message I changed the catch clause in the plugin file and attached the new logs reported on my server below.

```
# case 1 
[Error]
Copy file not found: /storage/emulated/0/iPhoneData/Pictures/학교종이/IMG_20230830_152558883.jpg, error: /storage/emulated/0/iPhoneData/Pictures/학교종이/IMG_20230830_152558883.jpg: open failed: EPERM (Operation not permitted)

[Parms] 
path: file:///storage/emulated/0/Android/data/com.schoolbell_e.schoolbell_e/files/intermediate.jpg
albumIdentifier: 학교종이

[Device info]
"os_version": "13",
"app_version": "5.0.51",
"device": "SM-F731N",


# case 2 
[Error]
Copy file not found: /storage/emulated/0/학교종이/IMG_20230830_144007181.jpg, error: /storage/emulated/0/학교종이/IMG_20230830_144007181.jpg: open failed: EPERM (Operation not permitted)

[Parms] 
path: file:///storage/emulated/0/Android/data/com.schoolbell_e.schoolbell_e/files/cdv_photo_000_high.jpg
albumIdentifier: 학교종이

[Device info]
"platform": "android",
"os_version": "13",

"device": "SM-S908N",


# case 3
[Error]
Copy file not found: /storage/emulated/0/학교종이/IMG_20230830_125834428.jpg, error: /storage/emulated/0/학교종이/IMG_20230830_125834428.jpg: open failed: EPERM (Operation not permitted)

[Parms] 
path: file:///storage/emulated/0/Android/data/com.schoolbell_e.schoolbell_e/files/%EA%B5%90%EC%9C%A1%EA%B3%B5%EB%8F%99%EC%B2%B4%EC%9D%98%20%EB%82%A0%20%EC%95%88%EB%82%B4%EB%AC%B8001.jpg
albumIdentifier: 학교종이

[Device info]
"platform": "android",
"os_version": "13",
"device": "SM-G996N",
```

**Comment by nkalupahana** [comment] 2023-08-31 17:03
Looks like the common thread between the devices is that they're on Android 13. Do you have the following in your manifest?
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
```

**Comment by fireonmac** [comment] 2023-09-05 02:26
The 'getAlbums()' method seems to retrieve all albums, not just those within the application specific path, but also from other paths that require MANAGE_EXTERNAL_STORAGE permission to access.

**Comment by nkalupahana** [comment] 2023-09-05 02:58
Got it, okay. getAlbums returning all albums is expected behavior. I think the best course of action, then, is to check for your bundle ID in getAlbums calls on Android when filtering.

**Comment by jabi11** [comment] 2023-09-06 09:42
Hi, I'm also running into same issue. Any ETA when it will be fixed?

**Comment by fireonmac** [comment] 2023-09-06 10:07
> 

Though II think that should fix the error.

> Hi, I'm also running into same issue. Any ETA when it will be fixed?


I may need to do some more tracking, but it seems that checking the bundle ID on Android 10 and above versions could resolve the issue.

**Comment by fireonmac** [comment] 2023-09-12 07:28
Android users with a version under 9 don't need bundle ID, but still get the permission error when they use any album in the sd card external storage. (https://developer.android.com/about/versions/11/privacy/storage)

[Android 9]
- getAlbums: Internal(O) External(O)
- copyFile: Internal(O) External(X)

[2023-09-12 15:28:06] REPORT.ERROR: ERROR_ Copy file not found: /storage/6439-3263/Gallery/학교종이/IMG_20230912_152806379.jpg, error: /storage/6439-3263/Gallery/학교종이/IMG_20230912_152806379.jpg (Permission denied)

**Comment by nkalupahana** [comment] 2023-09-15 15:24
@fireonmac are you saying this issue shows up for all albums, including ones you created using the app, or just when album names conflict? I'm confused about the status of this issue right now.

**Comment by fireonmac** [comment] 2023-09-19 03:04
@nkalupahana I think the problem is the album name conflict. Is it intentional to block saving images to albums on external storage? The problem I encountered was some of some of my users copy the folder in filesystem and paste it in SD card, so they are recognized when getAlbums() called, but can't copy files to there.

**Comment by nkalupahana** [comment] 2023-09-19 14:38
Maybe you need to specify a different permission in your manifest? Not sure what that would be though.

If the problem is an album name conflict, I would also recommend using a different album name that's less likely to conflict, or using some URL parser to determine what storage volume the album is on.

**Comment by nkalupahana** [comment] 2023-10-30 18:02
@fireonmac let me know if this would be useful, or if you need any help! Otherwise, I'll close this issue.

**Closed** 2023-11-03 15:28 UTC
