### ISSUE TITLE
Android: RuntimeException occurred on savePhoto()

### ISSUE THREAD

**Issue by cihakmar** [capacitor-community/media#34] opened 2023-02-01 12:51 UTC
**Describe the bug**
When trying to save photo on android, the function return erorr "RuntimeException occurred".

**Expected behavior**
Saving image to gallery

`Error: RuntimeException occurred
    at returnResult (vehicles_worldwide_in_2022:717:32)
    at win.androidBridge.onmessage (vehicles_worldwide_in_2022:692:21)`

**Comment by nkalupahana** [comment] 2023-02-01 15:06
Hi! Could you please send the full RuntimeException stack trace, and the code you're running on the JavaScript side that causes it?

**Comment by infinus-electronics** [comment] 2023-02-04 00:45
I am also facing the same issue,

stack trace:
`2023-02-04 00:36:41.780 30467-30534/io.ionic.starter E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at com.getcapacitor.community.media.MediaPlugin._saveMedia(MediaPlugin.java:209)
        at com.getcapacitor.community.media.MediaPlugin.savePhoto(MediaPlugin.java:77)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2023-02-04 00:36:41.780 30467-30534/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: io.ionic.starter, PID: 30467
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:772)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at com.getcapacitor.community.media.MediaPlugin._saveMedia(MediaPlugin.java:209)
        at com.getcapacitor.community.media.MediaPlugin.savePhoto(MediaPlugin.java:77)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) `

and the corresponding JS call:

`Media.savePhoto({path: data, album:"Pictures"}).then(console.log).catch(console.log);`

where data is a base64 jpg string "data:image/jpeg;base64,..." (console logged data right before calling savePhoto just to be sure)

I'm using the Android Studio Default JDK 11.0.12, running on emulated and physical Google Pixel 4A, API versions 31 and 33 respectively. I was not able to get this to work on either of them

**Comment by nkalupahana** [comment] 2023-02-04 02:03
Ah, I see! base64 URL handling is merged into the main branch, but not released yet. Should be releasing it in the next few days, I'll keep you updated!

**Comment by infinus-electronics** [comment] 2023-02-04 13:35
Ah i see, thanks!

**Comment by nkalupahana** [comment] 2023-02-04 21:34
@infinus-electronics package has been updated to 4.0.1!

**Closed by nkalupahana** 2023-02-04 21:34 UTC

**Comment by macsupport** [comment] 2023-02-06 06:10
Getting the same error with 4.0.1

**Comment by nkalupahana** [comment] 2023-02-06 06:11
@macsupport please open a new issue with your stack trace and the JS code you're running

**Comment by cihakmar** [comment] 2023-02-14 12:49
> Hi! Could you please send the full RuntimeException stack trace, and the code you're running on the JavaScript side that causes it?

`E/Capacitor/Plugin: RuntimeException occurred
    java.lang.RuntimeException: Source file not found: /direct-download/2022/01/22_SKODA_ENYAQ_COUPE_iV.jpg, error: /direct-download/2022/01/22_SKODA_ENYAQ_COUPE_iV.jpg: open failed: ENOENT (No such file or directory)
        at com.getcapacitor.community.media.MediaPlugin.copyFile(MediaPlugin.java:317)
        at com.getcapacitor.community.media.MediaPlugin._saveMedia(MediaPlugin.java:255)
        at com.getcapacitor.community.media.MediaPlugin.savePhoto(MediaPlugin.java:79)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:125)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:706)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
`


It looks like that plugin removes server url.

**Comment by macsupport** [comment] 2023-02-15 00:13
The code is pretty simple:






























*function scanDocument2() {  var image =
document.getElementById("myImage").src;return
Capacitor.Plugins.DocumentScanner.scanDocument({responseType:
'imageFilePath'}).then(function(result) {const scannedImages =
result.scannedImages;if (scannedImages.length > 0) {const scannedImage =
document.getElementById('myImage');if (scannedImage) {scannedImage.src =
Capacitor.convertFileSrc(scannedImages[0]);// scannedImage.src =
JSON.stringify("data:image/jpeg;base64," +
scannedImages[0]);localStorage.setItem("imageSrc",
scannedImage.src);setTimeout(function() {      Capacitor.Plugins.Media
  .savePhoto({          path: scannedImage.src,          album:
"Vetcalculators",        })        .then((r) => console.log(r))
.catch((e) => console.error(e));}, 1500);}}});}*



 RuntimeException occurred

                        java.lang.RuntimeException: Source file not found:
/_capacitor_file_/storage/emulated/0/Android/data/com.vetcalculators.sofie/files/Pictures/DOCUMENT_SCAN_0_20230214_161037945210687279549685.jpg,
error:
/_capacitor_file_/storage/emulated/0/Android/data/com.vetcalculators.sofie/files/Pictures/DOCUMENT_SCAN_0_20230214_161037945210687279549685.jpg:
open failed: ENOENT (No such file or directory)

                        at
com.getcapacitor.community.media.MediaPlugin.copyFile(MediaPlugin.java:317)

                        at
com.getcapacitor.community.media.MediaPlugin._saveMedia(MediaPlugin.java:255)

                        at
com.getcapacitor.community.media.MediaPlugin.savePhoto(MediaPlugin.java:79)

                        at java.lang.reflect.Method.invoke(Native Method)

                        at
com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)

                        at
com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)

                        at
com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)

                        at
android.os.Handler.handleCallback(Handler.java:942)

                        at
android.os.Handler.dispatchMessage(Handler.java:99)

                        at android.os.Looper.loopOnce(Looper.java:201)

                        at android.os.Looper.loop(Looper.java:288)

                        at
android.os.HandlerThread.run(HandlerThread.java:67)

Mike Sozanski DVM, DABVP

Check out my Veterinary Calculators: vetcalculators.com
<http://www.vetcalculators.com>
iOS <https://itunes.apple.com/us/app/vetcalculators/id1403466061?ls=1&mt=8>
and Android
<https://play.google.com/store/apps/details?id=com.vetcalculators.android>App
Available
